runtime: custom
env: flex

entrypoint: gunicorn -b :$PORT main:app --timeout 180

env_variables:
  DB_USER: "matrix"
  DB_PASS: "matrix"
  DB_NAME: "matrix"
  DB_HOST: "/cloudsql/writearm-brain:us-central1:writearm-brain"
  INSTANCE_CONNECTION_NAME: "writearm-brain:us-central1:writearm-brain"
  FLASK_SECRET_KEY: "your-secret-key-here"
  OPENAI_API_KEY: "your-openai-key-here"
  APP_USER: "GITM"
  APP_PASS: "GITM123"

beta_settings:
  cloud_sql_instances: writearm-brain:us-central1:writearm-brain

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
