steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/writearm-brain/writearm-app', '.']

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/writearm-brain/writearm-app']

  # Step 3: Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']  # Removed --quiet for verbose output

images:
  - 'gcr.io/writearm-brain/writearm-app'

options:
  logging: CLOUD_LOGGING_ONLY